### ISSUE TITLE
Фильтрация

### ISSUE THREAD

**Issue by preusx** [RadionovStalker/carblog_heroku2#7]
https://github.com/RadionovStalker/carblog_heroku2/blob/master/blog_engine/views.py#L74

Параметра, которые приходят от пользователя. Сначала валидируются(например с помощью формы). Затем происходит фильтрация по ним.

Эти две функции уже реализованы в библиотеке: https://github.com/carltongibson/django-filter. Пользуемся.

**Comment by RadionovStalker** [comment]
Есть ли смысл применять данный модуль для данного проекта, ведь там присутствует единственная фильтраций по категории?

**Comment by preusx** [comment]
Да. Вы-же учитесь сейчас. И даже так - будет работать значительно лучше сем сейчас.

**Comment by RadionovStalker** [comment]
Как-то у меня хуже получается постоянно использовать готовые модули, чем написать своё решение вручную. Потратил 3 часа только на то, чтобы при использовании django-filter работала пагинация, и то там есть костыль в виде бесконечного добавления номера страницу в url страницы (но оно работает). Это были танцы с бубном по "сдруживанию" пагинации и модуля фильтрования.  Теперь, будет поиск следующих костылей, чтобы правильно фильтровало категории django-treebeard. Также совершенно непонятно, как фильтровать переводимые поля (фильтр их просто не видет).
И самое главное, что практически никакой информации, как люди решали подобные вопросы - нет.
Собственно, к чему я это все пишу: если возникают большие трудности по налаживанию работы нескольких готовых модулей между собой , а еще и инфы нет по этому поводу в сети, то не лучше ли написать какое-то своё решение?
Я просто хочу узнать, что делать в таких ситуациях.

**Comment by RadionovStalker** [comment]
Если я должен перед фильтрацией сначала найти все подкатегории категории, по которым нужно будет потом фильтровать, как мне нужно тогда обойти базовую логику django-filter? Искать во вьюхе все подкатегории, а потом как-то их передавать в фильтр, или искать эти подкатегории уже в фильтре (т.е. что-то в нем переопределять, что именно хз), или вообще javascript-ом сразу искать подкатегории, вставлять их в url страницы, а потом только отправлять на сервер?

**Comment by RadionovStalker** [comment]
было так:
 def get_queryset(self):
        print("queryset")
        # print(self.request.session)
        print("get queryset")
        print(self.request.GET)
        if 'unfilter_btn' in self.request.GET:
            objects = Article.objects.filter(translations__language_code=get_language())
            return objects.order_by('-date_creation')
        if 'group_by' in self.request.GET:
            grouping = self.request.GET.getlist('group_by')
        else:
            grouping = 'no'
        # grouping = self.request.GET.get('group_by', 'no')
        print("it is grouping:")
        print(grouping)
        if grouping != 'no':
            categories = TreeCategory.objects.filter(id__in=grouping)
            ids_cat = list()
            for cat in categories:
                sub_categories = TreeCategory.get_tree(cat)
                for sub_cat in sub_categories:
                    if sub_cat.id not in ids_cat:
                        ids_cat.append(sub_cat.id)
            print(ids_cat)
            objects = Article.objects.filter(tree_category__id__in=ids_cat,  translations__language_code=get_language())
        else:
            objects = Article.objects.filter(translations__language_code=get_language())

        ordering = self.request.GET.get('order_by', '-date_creation')
        if ordering == 'like':
            return objects.annotate(q_count=Count('like')).order_by('q_count', '-date_creation')
        elif ordering == '-like':
            return objects.annotate(q_count=Count('like')).order_by('q_count', 'date_creation').reverse()
        else:
            return objects.order_by(ordering)

**Comment by RadionovStalker** [comment]
вот этот участок искал подкатегории:
 categories = TreeCategory.objects.filter(id__in=grouping)
            ids_cat = list()
            for cat in categories:
                sub_categories = TreeCategory.get_tree(cat)
                for sub_cat in sub_categories:
                    if sub_cat.id not in ids_cat:
                        ids_cat.append(sub_cat.id)
            print(ids_cat)
            objects = Article.objects.filter(tree_category__id__in=ids_cat,  translations__language_code=get_language())

**Comment by RadionovStalker** [comment]
```
 categories = TreeCategory.objects.filter(id__in=grouping)
            ids_cat = list()
            for cat in categories:
                sub_categories = TreeCategory.get_tree(cat)
                for sub_cat in sub_categories:
                    if sub_cat.id not in ids_cat:
                        ids_cat.append(sub_cat.id)
            print(ids_cat)
            objects = Article.objects.filter(tree_category__id__in=ids_cat,  translations__language_code=get_language())
```

**Comment by RadionovStalker** [comment]
было так:
```
    def get_queryset(self):
        print("queryset")
        # print(self.request.session)
        print("get queryset")
        print(self.request.GET)
        if 'unfilter_btn' in self.request.GET:
            objects = Article.objects.filter(translations__language_code=get_language())
            return objects.order_by('-date_creation')
        if 'group_by' in self.request.GET:
            grouping = self.request.GET.getlist('group_by')
        else:
            grouping = 'no'
        # grouping = self.request.GET.get('group_by', 'no')
        print("it is grouping:")
        print(grouping)
        if grouping != 'no':
            categories = TreeCategory.objects.filter(id__in=grouping)
            ids_cat = list()
            for cat in categories:
                sub_categories = TreeCategory.get_tree(cat)
                for sub_cat in sub_categories:
                    if sub_cat.id not in ids_cat:
                        ids_cat.append(sub_cat.id)
            print(ids_cat)
            objects = Article.objects.filter(tree_category__id__in=ids_cat,  translations__language_code=get_language())
        else:
            objects = Article.objects.filter(translations__language_code=get_language())

        ordering = self.request.GET.get('order_by', '-date_creation')
        if ordering == 'like':
            return objects.annotate(q_count=Count('like')).order_by('q_count', '-date_creation')
        elif ordering == '-like':
            return objects.annotate(q_count=Count('like')).order_by('q_count', 'date_creation').reverse()
        else:
            return objects.order_by(ordering)
```

**Comment by RadionovStalker** [comment]
этот участок искал подкатегории:
```
 categories = TreeCategory.objects.filter(id__in=grouping)
            ids_cat = list()
            for cat in categories:
                sub_categories = TreeCategory.get_tree(cat)
                for sub_cat in sub_categories:
                    if sub_cat.id not in ids_cat:
                        ids_cat.append(sub_cat.id)
            print(ids_cat)
```

**Comment by RadionovStalker** [comment]
Теперь не понятно, как что-то подобное передать в фильтр , или непосредственно реализовать в нем, иначе он просто фильтрует по переданной категории, а не по всем её подкатегориям.

**Comment by preusx** [comment]
Пишешь фильтр, который наследуется от стандартного, называешь TreeFilter - и оно работает.

Или, если проще - можно так: https://django-filter.readthedocs.io/en/master/ref/filters.html#method

**Comment by RadionovStalker** [comment]
Не уверен, что сделал по правилам, но сейчас оно фильтрует при помощи django-filter . Осталось добить пагинацию.
