### ISSUE TITLE
Используй ID

### ISSUE THREAD

**Issue by preusx** [RadionovStalker/carblog_heroku2#8]
https://github.com/RadionovStalker/carblog_heroku2/blob/master/blog_engine/views.py#L83

Зачем фильтровать по имени, если есть id? Причем не нужно совершенно знать о том, какой перевод использовать итп. SQL в принципе по целочисленным фильтрует быстрее, а по индексированным связям - еще быстрее.

**Comment by RadionovStalker** [comment]
Но я ведь тут ни по имени, ни по id, не фильтрую. Либо по датам вверх/вниз, либо по количеству лайков вверх/вниз. Или я не понял замечание?

**Comment by preusx** [comment]
tree_category__name__in

Строка не та.
