### ISSUE TITLE
N+

### ISSUE THREAD

**Issue by preusx** [RadionovStalker/carblog_heroku2#9]
https://github.com/RadionovStalker/carblog_heroku2/blob/557fe7f6abba17bf68f0b388c80a1c519859391a/blog_engine/views.py#L104    
Тут N+ запросов... А можно было сделать аннотацию: https://docs.djangoproject.com/en/2.1/topics/db/aggregation/

https://github.com/RadionovStalker/carblog_heroku2/blob/557fe7f6abba17bf68f0b388c80a1c519859391a/blog_engine/views.py#L102   
Тут можно было просто достать с помощью reverse relation, а не делать отдельный запрос. Как и комментарии ниже.

**Comment by RadionovStalker** [comment]
if self.request.user in article.like.all(): 
никак не могу понять, как для этого случая аннотацию применить

**Comment by preusx** [comment]
Можно просто вторым запросом:

```
liked = set(LikeConnection.objects.filter(
    article_id__in=articles,
    user_id=self.request.user.id
).values_list('article_id', flat=True))
```
А потом делать `article.id in liked`. Этот вариант самый удобный, потому как кеш для него запилить легко.

Можно подзапросом:  
https://docs.djangoproject.com/en/2.1/ref/models/expressions/

```
articles.annotate(is_liked=Exists(LikeConnection.objects.filter(
    article_id=OuterRef('id'),
    user_id=self.request.user.id
))
```

Можно использовать CASE конструкцию:  
https://docs.djangoproject.com/en/2.1/ref/models/conditional-expressions/#case

**Comment by RadionovStalker** [comment]
Я переделал на два разных варианта, тот запрос и проверку, но думаю, что ни один из них не  отвечает тому, о чем ты мне говоришь, т.к. я не могу осуществить запрос от Like, чтобы выбрать в них статью и пользователя, который лайкнул. Хотя Like  и должна быть промежуточной таблицей между User и Article, но как это устроенно в django я пока до конца так и не понял.
